# Generated by Django 5.2.3 on 2025-07-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount", models.IntegerField()),
                ("funded_amount", models.IntegerField()),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("36 months", "36 months"),
                            ("60 months", "60 months"),
                        ],
                        max_length=20,
                    ),
                ),
                ("interest_rate", models.FloatField()),
                ("installment", models.FloatField()),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "emp_length",
                    models.IntegerField(
                        choices=[
                            ("10+ years", "10+ years"),
                            ("9 years", "9 years"),
                            ("8 years", "8 years"),
                            ("7 years", "7 years"),
                            ("6 years", "6 years"),
                            ("5 years", "5 years"),
                            ("4 years", "4 years"),
                            ("3 years", "3 years"),
                            ("2 years", "2 years"),
                            ("1 year", "1 year"),
                            ("< 1 year", "< 1 year"),
                        ]
                    ),
                ),
                (
                    "home_ownership",
                    models.CharField(
                        choices=[
                            ("RENT", "RENT"),
                            ("MORTGAGE", "MORTGAGE"),
                            ("OWN", "OWN"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=20,
                    ),
                ),
                ("annual_income", models.IntegerField()),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("Not Verified", "Not Verified"),
                            ("Verified", "Verified"),
                            ("Source Verified", "Source Verified"),
                        ],
                        max_length=20,
                    ),
                ),
                ("issue_d", models.DateField()),
                ("payment_plan", models.CharField(max_length=20)),
                ("policy_code", models.CharField(max_length=20)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("credit_card", "credit_card"),
                            ("debt_consolidation", "debt_consolidation"),
                            ("home_improvement", "home_improvement"),
                            ("major_purchase", "major_purchase"),
                            ("small_business", "small_business"),
                            ("vacation", "vacation"),
                            ("wedding", "wedding"),
                            ("other", "other"),
                            ("car", "car"),
                            ("medical", "medical"),
                            ("moving", "moving"),
                            ("renewable_energy", "renewable_energy"),
                            ("vacation", "vacation"),
                            ("wedding", "wedding"),
                            ("other", "other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dti", models.IntegerField()),
                ("delinq_2yrs", models.IntegerField()),
                ("open_acc", models.IntegerField()),
                ("pub_rec", models.IntegerField()),
                ("revol_bal", models.IntegerField()),
                ("revol_util", models.IntegerField()),
                ("total_acc", models.IntegerField()),
                (
                    "initial_list_status",
                    models.CharField(choices=[("f", "f"), ("w", "w")], max_length=20),
                ),
                ("out_prncp", models.IntegerField()),
                ("out_prncp_inv", models.IntegerField()),
                ("total_pymnt", models.IntegerField()),
                ("total_pymnt_inv", models.IntegerField()),
                ("total_rec_int", models.IntegerField()),
                ("total_rec_late_fee", models.IntegerField()),
                ("recoveries", models.IntegerField()),
                ("last_pymnt_d", models.DateField()),
                ("collection_recovery_fee", models.IntegerField()),
                ("acc_now_delinq", models.IntegerField()),
                ("total_coll_amt", models.IntegerField()),
                ("total_cur_bal", models.IntegerField()),
                ("total_rev_hi_lim", models.IntegerField()),
                ("defaulter", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
