# Generated by Django 5.2.3 on 2025-07-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanmodel",
            name="emp_length",
            field=models.CharField(
                choices=[
                    ("10+ years", "10+ years"),
                    ("9 years", "9 years"),
                    ("8 years", "8 years"),
                    ("7 years", "7 years"),
                    ("6 years", "6 years"),
                    ("5 years", "5 years"),
                    ("4 years", "4 years"),
                    ("3 years", "3 years"),
                    ("2 years", "2 years"),
                    ("1 year", "1 year"),
                    ("< 1 year", "< 1 year"),
                ],
                max_length=20,
            ),
        ),
    ]
