# Generated by Django 5.2.3 on 2025-07-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_loanmodel_created_at_loanmodel_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanmodel",
            name="defaulter",
        ),
    ]
