# Generated by Django 5.2.3 on 2025-07-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_loanmodel_defaulter"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanmodel",
            name="defaulter",
            field=models.BooleanField(default=False),
        ),
    ]
