# Generated by Django 5.2.3 on 2025-07-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_loanmodel_defaulter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanmodel",
            name="collection_recovery_fee",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="funded_amount",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="issue_d",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="last_pymnt_d",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="out_prncp",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="out_prncp_inv",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="payment_plan",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="policy_code",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="revol_bal",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="total_acc",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="total_cur_bal",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="total_pymnt",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="total_pymnt_inv",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="total_rec_int",
        ),
        migrations.RemoveField(
            model_name="loanmodel",
            name="total_rev_hi_lim",
        ),
        migrations.AlterField(
            model_name="loanmodel",
            name="defaulter",
            field=models.BooleanField(),
        ),
    ]
