# Generated by Django 5.2.3 on 2025-07-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_loanmodel_collection_recovery_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanmodel",
            name="defaulter",
            field=models.BooleanField(default=False),
        ),
    ]
